#!/bin/sh
#this is script will only copy the "nitroslim" file to the "/usr/bin" place#
if [ $USER != root ]
then
    echo "Run install script as Root"
    exit 1
else
    :
fi


FILE=$(basename "$0")
CURRENT_DIR=$(readlink -f "$0" | sed -e "s/"$FILE"//")

echo -e "This is script will only copy the "nitroslim" executable file to the "/usr/bin" place.\nYou can do it with cp, if you want\n"
echo "Do you want to install Nitroslim? [y]es or no: " && read AW

if [ -z $AW ]
then
    :
elif [ $AW == "yes" ] || [ $AW == "y" ]
then
    :
elif [ $AW == "no" ] || [ $AW == "n" ]
then
    echo "Nitroslim not installed. Exiting."
    exit 0
else
    echo '"yes" or "no"'
    exit 1
fi

cp "$CURRENT_DIR/nitroslim" /usr/bin/
echo "Successful instaled"
