#!/bin/bash
#Nitroslim#
# License: GPL 2.0
# Autor: https://github.com/evertonstz 
#this scripts move your new selected wallpaper in nitrogen to your slim theme wallpaper#
#config file location#
VERSION="0.4"
#set some variables#
DIR=$(sed -e 's/file=//' -n -e '2,2p' /home/$USER/.config/nitrogen/bg-saved.cfg)
THEMENAME=$(awk '/current_theme/ { print $2}' /etc/slim.conf)
CONFIG="/home/$USER/.config/nitroslim.conf"

if [ -f "$CONFIG" ]
then
    :
else
    touch $CONFIG
    echo -e "#config file and cache for nitroslim blur#\nblur: 4\ncache: no\n#uncomment next line for setup a custom resolution#\n#resolution: 1440x900" >>  $CONFIG
fi



#checking for manual resolution#
if [[ -z $(sed -n '/#resolution:.*/p' "$CONFIG") ]]
then
    SCREENX=$(sed -n '/resolution:.*/p'  "$CONFIG" | awk '{print $2}' | sed 's/x.*//')
    SCREENY=$(sed -n '/resolution:.*/p'  "$CONFIG" | awk '{print $2}' | sed 's/.*x//')
else
    SCREENX=$(xrandr --verbose | grep *current | awk '{print $1}' | sed 's/x.*//')
    SCREENY=$(xrandr --verbose | grep *current | awk '{print $1}' | sed 's/.*x//')
fi


#check if can write in theme folder#
if [ -w /usr/share/slim/themes/ ]
then
    :
else
    echo "You don't have permission to write in /usr/share/slim/themes/. Try to run: sudo chmod -R 777 /usr/share/slim/themes/"
    exit 1
fi

#check if X are running#
if ! pgrep X &>/dev/null; then
        echo "Not running X."
	exit 1
fi

#dependences#
if ! type -p convert > /dev/null; then
        echo 'You must install "imagemagick" (pacman -S imagemagick).'
		exit 1
elif ! type -p xrandr > /dev/null; then
        echo "You must install "xrandr" (pacman -S xorg-xrandr)."
		exit 1
elif ! type -p notify-send > /dev/null; then
        echo "You must install "libnotify" (pacman -S libnotify)."
        exit 1
fi
if ! type -p nitrogen > /dev/null; then
        echo "You must install "nitrogen" (pacman -S nitrogen)."
        exit 1
fi
if ! type -p slim > /dev/null; then
        echo "You must install "slim" (pacman -S slim)."
fi

#Functions#
helpblur() {
    echo -e 'Blur usage: nitroslim -b [VALUE2] or --blur [VALUE2]\nUse a number to define the blur value. Use "0" or "none" for no blur. Default value for blur is 4.\nYou can also change blur in '$CONFIG'.\nIf "cache" in '$CONFIG' is "yes" (default is "no"), it will be cached.'
    exit 0
}

settingwall () {

    if [ -f /usr/share/slim/themes/$THEMENAME/background.png ]
    then
        rm /usr/share/slim/themes/$THEMENAME/background.png
    else
        :
    fi

    DIR=$(sed -e 's/file=//' -n -e '2,2p' /home/$USER/.config/nitrogen/bg-saved.cfg)

    #convert and move to the the theme folder#
    $(convert "$DIR" -gravity center -resize  "$SCREENX"x -crop x"$SCREENY"+0+0 -blur "$BLUR"x"$BLUR" "/usr/share/slim/themes/$THEMENAME/background.jpg")

#send a simple notify#
    notify-send "Slim is ready"
}

#make case#
case "$1" in
#check config file#
#blur#
-b | --blur) 
	#check if $2 are empty#
	if test -z $2
	then
		echo 'Use a numerical value for "blur" (ex: nitroslim -b 3).'
		exit 1
	fi
	#convert  "none" into a "0"#
	if [ $2 != "none" ]
		then
		BLUR="$2"
	else
		BLUR="0"
	fi
	#check if are asking for help#
	if [ $2  == "--help" ] || [ $2  == "-h" ]
	then
        helpblur
	fi
	#check if $2 are a number#
	if ! [[ "$BLUR" =~ ^[0-9]+$ ]] ; then
		exec >&2; echo "Error: Not a number"; exit 1
	fi
	#cache new blur#
    if [ $(awk '/cache:/ {print $2}' $CONFIG) == "yes" ]
    then
	    sed -i 's/blur:.*/blur: '$BLUR'/' "$CONFIG"
    fi
    DIR=$(sed -e 's/file=//' -n -e '2,2p' /home/$USER/.config/nitrogen/bg-saved.cfg)
    #put new blur#
        $(convert "$DIR" -gravity center -resize  "$SCREENX"x -crop x"$SCREENY"+0+0 -blur "$BLUR"x"$BLUR" "/usr/share/slim/themes/$THEMENAME/background.jpg")
    echo "Slim is ready."
    exit 0
    ;;
-c | --cache)
    if test -z $2
    then
        echo 'Use "nitroslim -c -h" for see if your cache are enabled and for help with cache command.'
        exit 0
    fi
    if [ $2  == "--help" ] || [ $2  == "-h" ]
    then
        if [ $(awk '/cache:/ {print $2}' $CONFIG) == "yes" ]
        then
            echo -e 'You ARE using cache mode.\nUse "nitroslim -c yes" or "nitroslim -c no" to setup cache.'
        else
            echo -e 'You ARE NOT using cache mode.\nUse "nitroslim -c yes" or "nitroslim -c no" to setup cache.'
        fi
        exit 0
    fi
    if [ $2 == "yes" ]
    then
        if [ $(awk '/cache:/ {print $2}' $CONFIG) == "yes" ]
        then
            echo "Cache is already ON"
        else
            sed -i 's/cache:.*/cache: yes/' "$CONFIG"
            echo "You set cache ON"
        fi
        exit 0
    elif [ "$2" == "no" ]
    then
        if [ $(awk '/cache:/ {print $2}' $CONFIG) == "no" ]
        then
            echo "Cache is already OFF"
        else
            sed -i 's/cache:.*/cache: no/' "$CONFIG"
            echo "You set cacho OFF"
        fi
        exit 0
    else
        echo -e 'Input Error.\nUse "nitroslim -c -h" for see if your cache are enabled and for help with cache command.'
        exit 1
    fi
    ;;
-s | --set)
    if [ -z "$2" ] #check if $2 are empty#
    then
        echo 'Input Error: Use "nitroslim -s -h" for help.'
        exit 1
    elif [ -z "$3" ]
    then
        echo 'Input Error: you need specify a image to set background.'
        exit 1
    fi
    

    #setting name#
    WALLNAME=$(basename "$3")
    #zoom fill#
    if [ $2 == "zoom-fill" ] || [ $2 == "zf" ]
    then
        if [ -f $3 ]
        then
            echo "Setting "$WALLNAME" as wallaper in Zoom Fill mode"
            $(nitrogen --save --set-zoom-fill "$3")
        else
            echo "File does not exist."
            exit 1
        fi
    #zoom#
    elif [ $2 == "zoom" ] || [ $2 == "z" ]
    then
        if [ -f $3 ]
        then
            echo "Setting "$WALLNAME" as wallaper in Zoom mode"
            $(nitrogen --save --set-zoom "$3")
        else
            echo "File does not exist."
            exit 1
        fi
    #tiled#
    elif [ $2 == "tiled" ] || [ $2 == "t" ]
    then
        if [ -f $3 ]
        then
            echo "Setting "$WALLNAME" as wallaper in Tiled mode"
            $(nitrogen --save --set-tiled "$3")
        else
            echo "File does not exist."
            exit 1
        fi
    #scaled#
    elif [ $2 == "scaled" ] || [ $2 == "s" ]
    then
        if [ -f $3 ]
        then
            echo "Setting "$WALLNAME" as wallaper in Scaled mode"
            $(nitrogen --save --set-scaled "$3")
        else
            echo "File does not exist."
            exit 1
        fi
    #centered#
    elif [ $2 == "centered" ] || [ $2 == "c" ]
    then
        if [ -f $3 ]
        then
            echo "Setting "$WALLNAME" as wallaper in Centered mode"
            $(nitrogen --save --set-centered "$3")
        else
            echo "File does not exist."
            exit 1
        fi
    #auto#
    elif [ $2 == "auto" ] || [ $2 == "a" ] 
    then
        if [ -f $3 ]
        then
            echo "Setting "$WALLNAME" as wallaper in Auto mode"
            $(nitrogen --save --set-auto "$3")
        else
            echo "File does not exist."
            exit 1
        fi
    #
    else
        echo 'Input Error: Use "nitroslim -s -h" for help.'
        exit 1
    fi
    #put blur#
    BLUR=$(awk '/blur:/ {print $2}' $CONFIG)
    settingwall
    exit 0
    ;;
#help#
-h | --help ) 
#print help#
echo -e "Usage: nitroslim [VALUE1] [COMMAND].\nVALUES:\n   -b (--blur): Use to setup blur radius (see nitroslim -b -h)\n   -c (--cache): Use to set cache on/off (see nitroslim -c -h)\n   -v (--version): See version\nIf you are having resolution problems, you can change resolution in $CONFIG\nBy: https://github.com/evertonstz"
    exit 0
  ;;
-v | --version )
    echo -e "Nitroslim $VERSION"
    exit 0
    ;;
*)#if no blur from imput, read the config file#
    BLUR=$(awk '/blur:/ {print $2}' $CONFIG)
    echo "Set your new wallpaper, blur is from your config file."
    ;;
esac

#run nitrogen#
$(nitrogen)

settingwall
